schema_version: '1.0'
citations:
  mode: selectedpubs
  selected:
    - Ramasubramani2020b
    - Ramasubramani2020
    - Dice_2019
    - simon2019
    - vyas_ramasubramani-proc-scipy-2018
    - adorf2018
    - ADORF2018220
    - Sinha:2014aa
sections:
  education:
    entries:
      - id: umich-phd
        display:
          - extended
      - id: umich-ms
        display:
          - extended
      - id: princeton-bse
        display:
          - compact
          - extended
      - id: lynbrook-high-school-degree
        display:
          - compact
          - extended
      - id: foothill-college-degree
        display:
          - compact
          - extended
      - id: johns-hopkins-university-degree
        display:
          - compact
          - extended
  research_experience:
    entries:
      - id: umich-glotzer-group-research-assistant
        display:
          - compact
          - extended
      - id: princeton-prud-homme-lab-thesis-researcher
        display:
          - compact
          - extended
      - id: ascr-ettrich-lab-undergraduate-researcher
        display:
          - compact
          - extended
      - id: princeton-brynildsen-lab-undergraduate-researcher
        display:
          - compact
          - extended
      - id: princeton-stone-lab-undergraduate-researcher
        display:
          - compact
          - extended
      - id: princeton-lewis-sigler-institute-undergraduate-researcher
        display:
          - compact
          - extended
      - id: princeton-shvartsman-lab-undergraduate-researcher
        display:
          - compact
          - extended
      - id: stanford-heller-lab-undergraduate-researcher
        display:
          - compact
          - extended
      - id: ucsc-cosmos-undergraduate-researcher
        display:
          - compact
          - extended
  work_experience:
    entries:
      - id: nvidia-senior-swe
        display:
          - compact
          - extended
      - id: d-c-energy-llc-senior-financial-analyst
        display:
          - compact
          - extended
      - id: priate-tutor-tutor
        display:
          - compact
          - extended
      - id: camp-galileo-summer-intern
        display:
          - compact
          - extended
  skills:
    entries:
      - id: languages
        display:
          - compact
          - extended
      - id: tools-frameworks
        display:
          - compact
          - extended
  projects:
    entries:
      - id: cudf
        display:
          - compact
          - extended
      - id: signac-framework-github-com-glotzerlab-signac
        display:
          - compact
          - extended
      - id: freud-github-com-glotzerlab-freud
        display:
          - compact
          - extended
      - id: hoomd-blue-github-com-glotzerlab-hoomd-blue
        display:
          - compact
          - extended
      - id: rowan-github-com-glotzerlab-rowan
        display:
          - compact
          - extended
      - id: coxeter-github-com-glotzerlab-coxeter
        display:
          - compact
          - extended
      - id: gsd-github-com-glotzerlab-gsd
        display:
          - compact
          - extended
      - id: tigerchat
        display:
          - compact
          - extended
  honors:
    entries:
      - id: beyster-computational-innovation-fellow-university-of-michigan
        display:
          - compact
          - extended
      - id: 2nd-place-micde-symposium-poster-competition
        display:
          - compact
          - extended
      - id: fellow-michigan-institute-for-computational-discovery-engineering
        display:
          - compact
          - extended
      - id: rackham-conference-travel-grant-university-of-michigan
        display:
          - compact
          - extended
      - id: departmental-nominee-beyster-computational-innovation-fellowship
        display:
          - compact
          - extended
      - id: che-outstanding-service-award-department-of-chemical-engineering
        display:
          - compact
          - extended
      - id: 1st-place-usb-molecular-biophysics-symposium
        display:
          - compact
          - extended
      - id: national-merit-scholar-national-merit-scholarship-corporation
        display:
          - compact
          - extended
      - id: valedictorian-lynbrook-high-school
        display:
          - compact
          - extended
      - id: ap-scholar-with-distinction-college-board
        display:
          - compact
          - extended
      - id: presidential-scholarship-semifinalist-us-department-of-education
        display:
          - compact
          - extended
      - id: trustee-distinguished-scholarship-declined-rice-university
        display:
          - compact
          - extended
      - id: century-scholarship-declined-rice-university
        display:
          - compact
          - extended
      - id: grand-scholar-center-for-talented-youth
        display:
          - compact
          - extended
  service_leadership:
    entries:
      - id: dei-student-advisory-board-board-member
        display:
          - compact
          - extended
      - id: chemical-engineering-graduate-society-gsac-representative
        display:
          - compact
          - extended
      - id: student-engagement-advisory-council-council-member
        display:
          - compact
          - extended
      - id: chemical-engineering-graduate-recruiting-chair
        display:
          - compact
          - extended
      - id: chemical-engineering-graduate-symposium-fundraising-chair
        display:
          - compact
          - extended
      - id: chemical-engineering-peer-mentoring-program-peer-mentor
        display:
          - compact
          - extended
      - id: um-mentorship-program-faculty-staff-mentor
        display:
          - compact
          - extended
      - id: chemical-engineering-graduate-society-representative
        display:
          - compact
          - extended
      - id: engineering-graduate-symposium-judge-recruiter
        display:
          - compact
          - extended
      - id: engineering-graduate-symposium-session-chair
        display:
          - compact
          - extended
      - id: healing-horse-clinic-bangalore-intern
        display:
          - compact
          - extended
      - id: national-honor-society-member
        display:
          - compact
          - extended
  teaching_experience:
    entries:
      - id: umich-ann-arbor-graduate-student-instructor-che-341-fluid-mechanics
        display:
          - compact
          - extended
      - id: 
          princeton-course-developer-cbe-439-quantitative-physiology-tissue-design
        display:
          - compact
          - extended
  grants:
    entries:
      - id: incite-proposal-pi-sharon-glotzer-jan-2019
        display:
          - compact
          - extended
      - id: xsede-proposal-pi-sharon-glotzer-jan-2018
        display:
          - compact
          - extended
      - id: xsede-proposal-pi-sharon-glotzer-jan-2017
        display:
          - compact
          - extended
      - id: xsede-proposal-pi-jens-glaser-aug-2016
        display:
          - compact
          - extended
  extracurricular:
    entries:
      - id: life-sciences-orchestra-2nd-trombone
        display:
          - compact
          - extended
      - id: princeton-orchestra-trombone-bass-trombone
        display:
          - compact
          - extended
      - id: daily-princetonian-senior-sports-writer
        display:
          - compact
          - extended
      - id: american-foreign-policy-contributor
        display:
          - compact
          - extended
      - id: lynbrook-varsity-tennis-captain
        display:
          - compact
          - extended
      - id: california-youth-symphony-lead-trombone
        display:
          - compact
          - extended
  affiliations:
    entries:
      - id: society-of-industrial-and-applied-mathematics-siam
        display:
          - compact
          - extended
      - id: american-physical-society
        display:
          - compact
          - extended
      - id: american-chemical-society
        display:
          - compact
          - extended
      - id: american-institute-of-chemical-engineers-aiche
        display:
          - compact
          - extended
  wetlab_skills:
    entries:
      - id: biology-techniques
        display:
          - compact
          - extended
      - id: chemistry-techniques
        display:
          - compact
          - extended
